### ISSUE TITLE
Renaming Routes, ejs files, form submits, etc

### ISSUE THREAD

**Issue by Libens-bufo** [lalysi/group-project-mvc-auth-todo#16]
We need to make the routes for a journal app rather than a todo app.

The mark complete/incomplete routes can probably be taken out. I will comment them out for now.

**Comment by Libens-bufo** [comment]
I did rename Todo.ejs to Entry.ejs in my other issue whose PR has been merged, see #18

**Comment by lalysi** [comment]
Excellent!
